import { Poppins } from "next/font/google";
import "../styles/globals.css";
import Head from "next/head";

const poppins = Poppins({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "@cezarupizarra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/cezaru.png" sizes="any" type="image/png" />
      </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
