import { Poppins } from "next/font/google";
import "../styles/globals.css";

const poppins = Poppins({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "@cezarupizarra | portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="shortcut icon"
        href="/cezaru.png"
        sizes="50x50"
        type="image/png"
      />
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
